### ISSUE TITLE
Glowing uranium model not working

### ISSUE THREAD

**Issue by AlexIIL** [EnderiumSmith/Nuclear-Foundation#1]
(migrated from https://www.reddit.com/r/feedthebeast/comments/5lks9f/coding110_how_do_i_make_the_ore_bits_on_a_block/)

I've come up with a coded solution for generating the positions, do you want it in a pull request?

**Comment by EnderiumSmith** [comment]
not sure. maybe a pull request but explain how it works. assign the textures to local sprites as im going to change which i use depending on blockstate.

**Comment by AlexIIL** [comment]
Hang on, it turns out that adding light to a block model was a bit finicky to get right so is taking a while.

**Comment by AlexIIL** [comment]
If #2 fixed this for you then I'll close this
